-- MySQL Script generated by MySQL Workbench
-- 05/14/16 03:08:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema WordFreqDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `WordNet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WordNet` (
  `language` VARCHAR(25) NOT NULL,
  `word` VARCHAR(25) NOT NULL,
  `lemma` VARCHAR(45) NULL,
  `freqrank` INT NULL,
  `antonyms` VARCHAR(100) NULL,
  `collocates` VARCHAR(500) NULL,
  `contexts` VARCHAR(100) NULL,
  `definitions` VARCHAR(400) NULL,
  `nativedefs` VARCHAR(400) NULL,
  `POS` VARCHAR(30) NULL,
  `rootwords` VARCHAR(100) NULL,
  `synonyms` VARCHAR(100) NULL,
  `synset` VARCHAR(45) NULL,
  `topics` VARCHAR(100) NULL,
  `WordNet_wordID` INT NOT NULL,
  `WordNet_wordID1` INT NOT NULL,
  PRIMARY KEY (`word`),
  UNIQUE INDEX `freqrank_UNIQUE` (`freqrank` ASC),
  INDEX `fk_WordNet_words1_idx` (`synset` ASC),
  UNIQUE INDEX `word_UNIQUE` (`word` ASC),
  CONSTRAINT `fk_WordNet_words1`
    FOREIGN KEY (`synset`)
    REFERENCES `words` (`synset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `languages` (
  `language` VARCHAR(25) NOT NULL);


-- -----------------------------------------------------
-- Table `Brown`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Brown` (
  `language` VARCHAR(25) NOT NULL DEFAULT 'English',
  `word` VARCHAR(25) CHARACTER SET 'big5' NOT NULL,
  `lemma` VARCHAR(45) NULL,
  `freqrank` INT NULL,
  `antonyms` VARCHAR(100) NULL,
  `collocates` VARCHAR(500) NULL,
  `contexts` VARCHAR(100) NULL,
  `definitions` VARCHAR(400) NULL,
  `nativedefs` VARCHAR(400) NULL,
  `POS` VARCHAR(30) NULL,
  `rootwords` VARCHAR(100) NULL,
  `synonyms` VARCHAR(100) NULL,
  `topics` VARCHAR(100) NULL,
  `WordNet_wordID` INT NOT NULL,
  `WordNet_wordID1` INT NOT NULL,
  PRIMARY KEY (`word`),
  UNIQUE INDEX `freqrank_UNIQUE` (`freqrank` ASC),
  UNIQUE INDEX `word_UNIQUE` (`word` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wordlists` (
  `listname` VARCHAR(50) NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `listweight` FLOAT NOT NULL,
  UNIQUE INDEX `listname_UNIQUE` (`listname` ASC),
  PRIMARY KEY (`listname`),
  INDEX `fk_wordlists_languages1_idx` (`language` ASC),
  CONSTRAINT `fk_wordlists_languages1`
    FOREIGN KEY (`language`)
    REFERENCES `languages` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wordlists_WordNet1`
    FOREIGN KEY (`language`)
    REFERENCES `WordNet` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wordlists_Brown1`
    FOREIGN KEY (`language`)
    REFERENCES `Brown` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `words` (
  `language` VARCHAR(25) NULL,
  `word` VARCHAR(25) NOT NULL,
  `lemma` VARCHAR(25) NULL,
  `freqscore` INT NULL,
  `freqrank` INT NOT NULL,
  `antonyms` VARCHAR(100) NULL,
  `collocates` VARCHAR(500) NULL,
  `contexts` VARCHAR(100) NULL,
  `definitions` VARCHAR(400) NULL,
  `nativedefs` VARCHAR(400) NULL,
  `POS` VARCHAR(30) NULL,
  `rootwords` VARCHAR(100) NULL,
  `synonyms` VARCHAR(100) NULL,
  `synset` VARCHAR(50) NULL,
  `topics` VARCHAR(100) NULL,
  PRIMARY KEY (`word`, `freqrank`),
  UNIQUE INDEX `freqrank_UNIQUE` (`freqrank` ASC),
  UNIQUE INDEX `word_UNIQUE` (`word` ASC),
  INDEX `fk_words_WordNet3_idx` (`lemma` ASC),
  INDEX `fk_words_WordNet4_idx` (`antonyms` ASC),
  INDEX `fk_words_WordNet5_idx` (`collocates` ASC),
  INDEX `fk_words_WordNet7_idx` (`contexts` ASC),
  INDEX `fk_words_WordNet8_idx` (`definitions` ASC),
  INDEX `fk_words_WordNet9_idx` (`nativedefs` ASC),
  INDEX `fk_words_WordNet10_idx` (`POS` ASC),
  INDEX `fk_words_WordNet11_idx` (`rootwords` ASC),
  INDEX `fk_words_WordNet13_idx` (`synonyms` ASC),
  INDEX `fk_words_WordNet14_idx` (`topics` ASC),
  INDEX `fk_words_wordlists1_idx` (`language` ASC),
  CONSTRAINT `fk_words_WordNet2`
    FOREIGN KEY (`freqrank`)
    REFERENCES `WordNet` (`freqrank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet1`
    FOREIGN KEY (`word`)
    REFERENCES `WordNet` (`word`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet3`
    FOREIGN KEY (`lemma`)
    REFERENCES `WordNet` (`lemma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet4`
    FOREIGN KEY (`antonyms`)
    REFERENCES `WordNet` (`antonyms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet5`
    FOREIGN KEY (`collocates`)
    REFERENCES `WordNet` (`collocates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet6`
    FOREIGN KEY (`collocates`)
    REFERENCES `WordNet` (`collocates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet7`
    FOREIGN KEY (`contexts`)
    REFERENCES `WordNet` (`contexts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet8`
    FOREIGN KEY (`definitions`)
    REFERENCES `WordNet` (`definitions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet9`
    FOREIGN KEY (`nativedefs`)
    REFERENCES `WordNet` (`nativedefs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet10`
    FOREIGN KEY (`POS`)
    REFERENCES `WordNet` (`POS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet11`
    FOREIGN KEY (`rootwords`)
    REFERENCES `WordNet` (`rootwords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet12`
    FOREIGN KEY (`rootwords`)
    REFERENCES `WordNet` (`rootwords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet13`
    FOREIGN KEY (`synonyms`)
    REFERENCES `WordNet` (`synonyms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_WordNet14`
    FOREIGN KEY (`topics`)
    REFERENCES `WordNet` (`topics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_wordlists1`
    FOREIGN KEY (`language`)
    REFERENCES `wordlists` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_wordlists2`
    FOREIGN KEY (`language`)
    REFERENCES `wordlists` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown1`
    FOREIGN KEY (`language`)
    REFERENCES `Brown` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown2`
    FOREIGN KEY (`word`)
    REFERENCES `Brown` (`word`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown3`
    FOREIGN KEY (`lemma`)
    REFERENCES `Brown` (`lemma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown4`
    FOREIGN KEY (`antonyms`)
    REFERENCES `Brown` (`antonyms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown5`
    FOREIGN KEY (`collocates`)
    REFERENCES `Brown` (`collocates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown6`
    FOREIGN KEY (`contexts`)
    REFERENCES `Brown` (`contexts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown7`
    FOREIGN KEY (`definitions`)
    REFERENCES `Brown` (`definitions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown8`
    FOREIGN KEY (`nativedefs`)
    REFERENCES `Brown` (`nativedefs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown9`
    FOREIGN KEY (`POS`)
    REFERENCES `Brown` (`POS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown10`
    FOREIGN KEY (`rootwords`)
    REFERENCES `Brown` (`rootwords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown11`
    FOREIGN KEY (`synonyms`)
    REFERENCES `Brown` (`synonyms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_words_Brown12`
    FOREIGN KEY (`topics`)
    REFERENCES `Brown` (`topics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
